apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  #namespace is not really usefull is small project --> remove the line and it will be in default namespace
  namespace: mongo 
data:
  #database_url: mongodb-service <-- without namespace
  database_url: mongodb-service.database
                #<url>.<namespace>
