apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  #namespace is not really usefull is small project --> remove the line and it will be in default namespace
  namespace: mongo
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
#usename and password must be base64 encoded
#terminal : echo -n 'username' | base64
#terminal : echo -n 'password' | base64
